dist: bionic

language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules

sudo: required

addons:
  chrome: stable

before_install:
  - sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
  - sudo chown root:$USER /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - export CHROME_BIN=google-chrome-stable
  - npm run-script prebuild
  - npm run-script build
  - npm test
